# Copyright (c) rikiya@stanford.edu 2021
# Autogenerated by SWE for Science kickstart generator - www.sweforscience.com - www.twitter.com/sweforscience 

SHELL := /bin/bash
help: ## This help dialog.
	@egrep '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

# Simple makefile that has a bunch of stuff that we care about.
venv-setup: ## set up the py virtual environment
	/usr/bin/env python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip && pwd && pip install -r py/requirements.txt

venv-freeze: ## freeze the current python requirements. Use before committing
	. venv/bin/activate && pip freeze > py/requirements.txt

venv-clean: ## clean the current venv
	rm -rf venv

# 1. you can run all tests with "make test"
test: ## run all tests
	cd py && /usr/bin/env python3 -m unittest discover -p '*unittest.py' -v ; cd -



# 2. you can create a docker file with make docker
docker-build: ## build a docker container called house_postdoc/webserver:1.0
	docker build -t house_postdoc/webserver:1.0 .




serverless-setup: ## set up infra to push webserver to AWS lambda
	cd py && \
	npm install serverless && \
	npm install --save-dev serverless-wsgi serverless-python-requirements && \
	aws configure

setup: venv-setup serverless-setup
all: test
