#!/usr/bin/env python3
# Copyright (c) rikiya@stanford.edu 2021
# Autogenerated by SWE for Science kickstart generator - www.sweforscience.com - www.twitter.com/sweforscience

''' This is the python file that contains unittests and most code for house_postdoc '''

import subprocess
import tempfile
import unittest

import numpy as np
from PIL import Image

import house_postdoc_lib


class Test(unittest.TestCase):
    save_path = 'tmp'

    def set_up_turtle(self):
        self.my_turtle = house_postdoc_lib.MyTurtle(draw_speed=0)
        WIDTH, HEIGHT = 800, 600
        self.my_turtle.screen.setup(WIDTH + 8, HEIGHT + 8)

    def set_up_functions(self):
        self.set_up_turtle()
        self.draw_functions = [self.my_turtle.draw_rectangle, self.my_turtle.draw_triangle,\
            self.my_turtle.draw_window, self.my_turtle.draw_door, self.my_turtle.draw_garage,\
            self.my_turtle.draw_cloud, self.my_turtle.draw_tree, self.my_turtle.draw_house,\
            self.my_turtle.draw_sun]
        self.objects = ['rectangle', 'triangle', 'window', 'door', 'garage', 'cloud', 'tree', 'house', 'sun']

    def test_all(self):
        self.set_up_functions()
        for fnc, object_name in zip(self.draw_functions, self.objects):
            self.set_up_turtle()
            fnc()
            self.my_turtle.my_turtle.hideturtle()
            self.my_turtle.save_image(object_name=object_name, image_type='test', save_path=self.save_path)
            self.my_turtle.my_turtle.screen.clear()
            test_array = np.array(Image.open(f'{self.save_path}/test_{object_name}.jpg'))
            reference_array = np.array(Image.open(f'references/reference_{object_name}.jpg'))
            self.assertTrue(np.array_equal(test_array, reference_array))


if __name__ == '__main__':
    tmp_dir = tempfile.TemporaryDirectory()
    Test.save_path = tmp_dir.name
    unittest.main()
    tmp_dir.cleanup()
