#!/usr/bin/env python3
# Copyright (c) rikiya@stanford.edu 2021
# Autogenerated by SWE for Science kickstart generator - www.sweforscience.com - www.twitter.com/sweforscience

''' This is the command line interface to save reference images. '''
''' Has to run this program from the root directory of this GitHub repo '''

import sys, os

import house_postdoc_lib


if __name__ == '__main__':
    print(os.environ["PATH"])
    # set up
    my_turtle = house_postdoc_lib.MyTurtle(draw_speed=0)
    WIDTH, HEIGHT = 800, 600
    my_turtle.screen.setup(WIDTH + 8, HEIGHT + 8)

    # save reference_rectangle.jpg in tmp directory
    my_turtle.draw_rectangle(x_length=150, y_length=120)
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='rectangle', image_type='reference')
    print('reference rectangle image saved successfully')

    # save reference_triangle.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_triangle(base_length=150)
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='triangle', image_type='reference')
    print('reference triangle image saved successfully')

    # save reference_window.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_window(window_size=40)
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='window', image_type='reference')
    print('reference window image saved successfully')

    # save reference_door.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_door(x_length=40, y_length=80)
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='door', image_type='reference')
    print('reference door image saved successfully')

    # save reference_garage.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_garage()
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='garage', image_type='reference')
    print('reference garage image saved successfully')

    # save reference_cloud.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_cloud()
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='cloud', image_type='reference')
    print('reference cloud image saved successfully')

    # save reference_tree.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_tree()
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='tree', image_type='reference')
    print('reference tree image saved successfully')

    # save reference_house.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_house()
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='house', image_type='reference')
    print('reference house image saved successfully')
    
    # save reference_sun.jpg in tmp directory
    my_turtle.my_turtle.clear()
    my_turtle.my_turtle.reset()
    my_turtle.my_turtle.speed(0)
    my_turtle.draw_sun()
    my_turtle.my_turtle.hideturtle()
    my_turtle.save_image(object_name='sun', image_type='reference')
    print('reference sun image saved successfully')

    sys.exit(0)