#!/usr/bin/env python3
# Copyright (c) rikiya@stanford.edu 2021
# Autogenerated by SWE for Science kickstart generator - www.sweforscience.com - www.twitter.com/sweforscience

''' This is the command line interface to save reference images. '''
''' Has to run this program from the root directory of this GitHub repo '''

import sys, os

from house_postdoc_lib import *


class SaveReferenceImage():
    def set_up_turtle(self):
        self.my_turtle = MyTurtle(draw_speed=0)
        WIDTH, HEIGHT = 800, 600
        self.my_turtle.screen.setup(WIDTH + 8, HEIGHT + 8)

    def set_up_functions(self):
        self.set_up_turtle()
        self.DRAW_FUNCTIONS = [self.my_turtle.draw_rectangle, self.my_turtle.draw_triangle,\
            self.my_turtle.draw_window, self.my_turtle.draw_door, self.my_turtle.draw_garage,\
            self.my_turtle.draw_cloud, self.my_turtle.draw_tree, self.my_turtle.draw_house,\
            self.my_turtle.draw_sun]
        self.OBJECTS = ['rectangle', 'triangle', 'window', 'door', 'garage', 'cloud', 'tree', 'house', 'sun']

    def save_reference_images(self):
        self.set_up_functions()
        for fnc, object_name in zip(self.DRAW_FUNCTIONS, self.OBJECTS):
            self.set_up_turtle()
            fnc()
            self.my_turtle.my_turtle.hideturtle()
            self.my_turtle.save_image(object_name=object_name, image_type='reference')
            self.my_turtle.my_turtle.screen.clear()
            print(f'reference {object_name} image saved successfully')

if __name__ == '__main__':
    SaveReferenceImage().save_reference_images()
