#!/usr/bin/env python3
# Copyright (c) rikiya@stanford.edu 2021
# Autogenerated by SWE for Science kickstart generator - www.sweforscience.com - www.twitter.com/sweforscience 

''' This is the main command line interface for house_postdoc. '''

import argparse
import logging
import sys

import house_postdoc_lib

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='house_postdoc')
    parser.add_argument('action', choices=['add', 'subtract'], help='Action to take')
    parser.add_argument('-l', '--left', required=True, type=float, help='the number on the left')
    parser.add_argument('-r', '--right', required=True, type=float, help='the number on the right')
    parser.add_argument('-v', '--verbose', default=False, action="store_true",
                        help="print details")
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.INFO if not args.verbose else logging.DEBUG,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler("debug.log"),
            logging.StreamHandler()
        ]
    )

    logging.info('starting up!')
    lval = args.left
    rval = args.right
    logging.debug('operation is %s' % args.action)
    if args.action == 'add':
        print(house_postdoc_lib.add(lval, rval))
    elif args.action == 'subtract':
        print(house_postdoc_lib.sub(lval, rval))
    sys.exit(0)
